"""Subclass of MainFrameUI, which is generated by wxFormBuilder."""

import wx
import SVGConvertorUI

# Implementing MainFrameUI
class MainFrame( SVGConvertorUI.MainFrameUI ):
	def __init__( self, parent ):
		SVGConvertorUI.MainFrameUI.__init__( self, parent )

	# Handlers for MainFrameUI events.
	def addFiles( self, event ):
		# TODO: Implement addFiles
		pass

	def addDirectory( self, event ):
		# TODO: Implement addDirectory
		pass

	def removeFiles( self, event ):
		# TODO: Implement removeFiles
		pass

	def removeAll( self, event ):
		# TODO: Implement removeAll
		pass

	def convert( self, event ):
		# TODO: Implement convert
		pass

	def toggleFormatVersion( self, event ):
		# TODO: Implement toggleFormatVersion
		pass

	def disableOutputDirPicker( self, event ):
		# TODO: Implement disableOutputDirPicker
		pass


