"""Subclass of MainFrameUI, which is generated by wxFormBuilder."""

import wx
import SVGConvertorUI

# Implementing MainFrameUI
class MainFrame( SVGConvertorUI.MainFrameUI ):
	def __init__( self, parent ):
		SVGConvertorUI.MainFrameUI.__init__( self, parent )

	# Handlers for MainFrameUI events.
	def initMainFrame( self, event ):
		# TODO: Implement initMainFrame
		pass

	def addFiles( self, event ):
		# TODO: Implement addFiles
		pass

	def addDirectory( self, event ):
		# TODO: Implement addDirectory
		pass

	def removeFiles( self, event ):
		# TODO: Implement removeFiles
		pass

	def removeAll( self, event ):
		# TODO: Implement removeAll
		pass

	def export( self, event ):
		# TODO: Implement convert
		pass

	def toggleTypeVersion( self, event ):
		# TODO: Implement toggleTypeVersion
		pass

	def toggleExportDirPicker( self, event ):
		# TODO: Implement toggleExportDirPicker
		pass


